### ISSUE TITLE
Scipy 0.15 not working with SVD

### ISSUE THREAD

**Issue by echristi** [jtwhite79/pyemu#1]
FYI - I couldn't not get parameter identifiability to work when running with Scipy 0.15.  Rolling back to 0.14 worked.  In the error_variance_example notebook it would fail on the first code line under parameter identifiability.  It appeared to be an issue with la.svd, "LAPACK function dgesdd_lwork could not be found"

**Comment by jtwhite79** [comment]
Seems like this is might be related to switch in Scipy from linpack_lite to lapack...Which version of Scipy - 0.15.X?  I tested it with Scipy 0.15.1 and the ```scipy.linalg.svd()``` routine completes without any problems.

**Comment by echristi** [comment]
It was Scipy 0.15.1,  updated when I updated anaconda.

**Comment by jtwhite79** [comment]
I've tested the error_variance_example notebook with 0.15.1 (installed with miniconda) on both mac and windows without trouble.  Can import the ```scipy.linalg``` module and try the SVD on a generic ```numpy.ndarray```?
