### ISSUE TITLE
nested list format for the helper function to generate the PEST control file 

### ISSUE THREAD

**Issue by flydream0428** [jtwhite79/pyemu#102]
In the function doc, it says the nested format is like this ["lpf.hk",[0,1,2,]]. However, to make it work, it should be in the format like the one below 
[["lpf.hk",0], ["lpf.hk",1]],["lpf.hk",2]]

**Comment by jtwhite79** [comment]
Good question @flydream0428 . `["lpf.hk",[0,1,2]]` will result in one set of HK pars (of whatever spatial distribution) and apply those pars to layers 1,2 and 3.  The other form, `[["lpf.hk",0], ["lpf.hk",1]],["lpf.hk",2]]`, will result in separate sets of HK parameters for each layer listsed.  I realize this might be confusing but its a way to share parameter sets across multiple model input arrays.
