### ISSUE TITLE
BED BUGS INFESTATION WORLDWIDE SPREADING LIKE WILD FIRES

### ISSUE THREAD

**Issue by JOPESTKIL** [jtwhite79/pyemu#110]
BEDBUGS INFESTATION SPREADING LIKE WILD FIRES
What They Look Like: Flat oval body with six legs, about the size of an apple seed that can be either brown or reddish brown.Typical ‘Hood: Can be found around the world, but recent outbreaks have centered in the United States, Canada, the UK, and other parts of Europe. Bed bugs are found in environments where many people cycle through on a given day—this includes apartments, hostels and hotels, trains, buses, and dorm rooms. Some theorists suggest that recent bed bug outbreaks are due to an increase in international travel, since the bugs can easily hide in luggage, bags, clothing, or bedding.Home Headquarters: Unsurprisingly, these pests love to hang out in and around the bed. Bed bugs’ small, flat bodies allow them to hide quite easily in seams of mattresses, bed frames, headboards, other bedroom furniture, behind wallpaper, in clothing, or any other household clutter.Fave Snacks: Blood. Bed bugs can live for up to a year in between “meals.”Danger Zone: Bed bugs don’t transmit diseases and are not considered a public health hazard. Bites cause itching, and dealing with an infestation can cause anxiety and insomnia. In some cases, bites can trigger a serious allergic reaction, but this is fairly rare.How to Ditch ‘Em: Unfortunately, getting rid of these little critters is hardly a walk in the park. First, all surfaces where bed bugs might dwell (sheets, pillows, towels, clothing, curtains, etc.) need to be washed in hot water and dried at the hottest setting for at least 30 minutes. Next, scrub the mattress with a stiff brush and vacuum it and the surrounding room thoroughly, disposing of the vacuum cleaner bags immediately. Cover the mattress in a bed bug cover (available at most home goods stores) or toss it if it’s really been infested. Be careful when trashing bed-buggy items—wrap anything in heavy plastic and packing tape and label it clearly so others know it contains bed bugs. Seal up peeling wallpaper and cracks in floorboards to remove future hiding spots, and clear up any household clutter around the bedroom. Pure essential oils (cinnamon, lemongrass, clove, peppermint, lavender, thyme, tea tree, and eucalyptus) can repel bed bugs from setting up shop in the first place, so spray ‘em in your suitcase before heading out on a trip and before coming home again. https://www.jopestkil.com/

**Comment by mnfienen-usgs** [comment]
SPAM

**Comment by jwhite-usgs** [comment]
Yup - I reported this crap to github...

**Comment by JOPESTKIL** [comment]
Why do some react so much in a negative way. Bed bugs are now not something to hide. They are there and more so in high class facilities, flights, homes, institutions and many others. https://www.jopestkil.com
