### ISSUE TITLE
uniform distributions for draw

### ISSUE THREAD

**Issue by mnfienen-usgs** [jtwhite79/pyemu#14]
OK - got a strange bug. I worked on it but couldn't quite sort it out....

With the new functionality to allow making a draw from either a uniform or Gaussian distribution, I hit trouble when sampling more than once.

Check out notebook `NSMCexample_freyberg.ipynb` in `examples`. If you never specify `how='uniform'` then sampling is always made as Gaussian (the default). Cool. If you specity `how='gaussian'`, same (as expected) behavior. **But**, if you make a draw specifying `how='uniform'` and *then* make a subsequent draw using `Gaussian` (either explicitly or by not specifying `how` and thus going default style) a strange set of exceptions get thrown that I haven't been able to get to the bottom of.

The notebook in my branch `master_mnf` illustrates this behavior.

**Comment by jtwhite79** [comment]
Looks like this is a notebook problem - if I download the notebook as a script, it runs without problems.  I try to find a way to debug in the notebook.
