### ISSUE TITLE
Issue with calculating correlation coefficients from Covariance matrix

### ISSUE THREAD

**Issue by Neilt100** [jtwhite79/pyemu#20]
Hi,

I've been trying to use the    to_person    method to convert a covariance matrix (from a jco file) to a correlation coefficient matrix, but I get an error:  ''''assert not self.isdiagonal''''.  

The covariance matrix I'm passing is diagonal (167 x 167).  Are there some methods within pyemu to correctly convert the covariance matrix so that it can be used by the to_pearson method?  Apologies if there is something obvious I'm missing that is explained elsewhere.

Thanks.

**Comment by jtwhite79** [comment]
So the Pearson coef between any row-col pair in a covariance matrix is related to the covariate between the row col - the off diagonal value at index (row-1,col-1).  Since your covariance matrix is diagonal, there no nonzero off diagonals...so nothing to calculate. Does that make sense?

**Comment by Neilt100** [comment]
Yes, that does make sense.  As I gradually understand it more, pyemu is becoming a much appreciated resource. Thanks.
