### ISSUE TITLE
PstFromFlopyModel expects pilot points

### ISSUE THREAD

**Issue by mnfienen-usgs** [jtwhite79/pyemu#24]
Ran into a problem with PstFromFlopyModel in which methods bombed if pp_props was not set. I made traps to try and allow subsets of properties to be set. I committed them in develop.

**Comment by mnfienen-usgs** [comment]
Oh - and relatedly, had trouble when  trying to use bc_props (specifically well pumping rates) as bc_props = [["wel.flux",None]] which is similar to your example notebook. Check out the `PST_to_pyemu_to_Schur_Overview.ipynb` notebook.

**Comment by jtwhite79** [comment]
got this tuned up.  Notebook at least gets an ``noptmax`` = 0 to run.
