### ISSUE TITLE
inschek chokes with <100K observations

### ISSUE THREAD

**Issue by mnfienen-usgs** [jtwhite79/pyemu#25]
Another small issue with automatically setting up PST from flopy model. `inschek` chokes with >100K observations, so can't use it to populate starting values for observations. In my example, I just removed some potential obs from HYDMOD, but might want to figure a way around that...

**Comment by jtwhite79** [comment]
I've seen that too. For hydmod, smp or hob, we can fix this by loading the output files with pandas and replacing values. But for other arbitrary instruction files...

**Comment by mnfienen-usgs** [comment]
kewl. should we just detect if NOBS for a given INS file is 100K or greater and, if so, warn about no INSCHEK run and populate with some dummy obs value like -9999 or 1.0 or something?

**Comment by jtwhite79** [comment]
i think it does populate with dummy Vals now. Let me know if it doesn't...

I'll prob just recompile inschek to process more obs.

**Comment by mnfienen-usgs** [comment]
since inschek bombed, pyemu didn't get the chance to write values. I think either we fix inschek or trap for large number of vars prior to calling inschek

**Comment by langevin-usgs** [comment]
Would be nice to rewrite inscheck so that it allocates more memory if needed, instead of hardwiring an upper limit.

**Comment by jtwhite79** [comment]
Ok, Mike - we should trap for that, at least for hymod, hob and smp files since we have knowledge of the output file structure.

Chris - I agree, but In fortran, that's not so fun. I guess you would have to read through the instruction file once to get the number of observations, then rewind it and process?  I haven't looked at the inschek code closely, but I can foretell a wicked nest of goto statements :)

**Comment by langevin-usgs** [comment]
Lately, we've been dynamically reallocating arrays on the fly, unless we now the size up front.

**Comment by jwhite-usgs** [comment]
Finally this has a solution - `Pst` now has a `process_output_files()` method that uses pure python instruction file processing.  Its def not as robust as INSCHEK but it removes the need to run a pre-compiled binary (and so far it is orders of magnitude faster than INSCHEK)
