### ISSUE TITLE
pst.write() iterates through n characters (rather than n paths) if pst.model_command value is changed.

### ISSUE THREAD

**Issue by wzell-usgs** [jtwhite79/pyemu#27]

**Comment by wzell-usgs** [comment]
Maybe cast this as a list rather than a string.

**Comment by jtwhite79** [comment]
I've messed this up too - just added an overload of __setattr__ to Pst that traps for a str instead of a list.  Seems to be working.

**Comment by wzell-usgs** [comment]
Oops! So it was my fault for over-writing a list with string. Duh.

**Comment by jtwhite79** [comment]
There can be multiple model commands (the numcom var in the control data section)  but I've messed up this up the same way several times so it needed to be fixed anyway.
