### ISSUE TITLE
plotting coming soon

### ISSUE THREAD

**Issue by jtwhite79** [jtwhite79/pyemu#29]
plotting needs:

Pst.plot() - 1to1 (by groups) (if res is available), parameter (and forecast) historgrams (if pest++ unc summaries are available)

Ensemble.plot() - historgrams (several per page, prob multipage pdf), support for several Ensembles on same plots to compare histrograms (and changes), add initial/observed values from Pst (if avail)

Schur.plot() - bar charts of prior/post/reduce uncertainty for pars and forecasts.  Optionally historgrams if initial and final par/forecast values are avail.  

ErrVar.plot() - stacked bar charts for each forecast. option to add Schur posterior as a horizontal line

**Comment by jtwhite79** [comment]
Initial plotting support is in.  Most of it is attached to the Pst.plot() and uses the "kind" keyword for the type of plot to make.  More to come...

**Comment by mnfienen-usgs** [comment]
Worked more on plotting (mostly in the weeds). But....Travis isn't installing correctly for testing. Getting these errors for Python 2.7 3.5 (but 3.6 passes):

```38.29s$ conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas nose matplotlib jupyter notebook cartopy
Solving environment: / - - \ | / / - \ \ | | / - - \ \ | | / - \ \ | | / - - \ | / / - \ \ \ | / - - \ \ | | / / - \ \ | / \ | / / - \ \ | / - - \ | | \ | | / / / - failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=2.7
  - ruamel_yaml -> python[version='>=3.6,<3.7.0a0']
Use "conda info <package>" to see the dependencies for each package.
The command "conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas nose matplotlib jupyter notebook cartopy" failed and exited with 1 during .
Your build has been stopped.```

**Comment by jtwhite79** [comment]
I'm getting them too as of Friday.  Looks like conda changed their yaml package and it's only 3.6.  I'll dig around - I bet others are having this issue too.

**Comment by mnfienen-usgs** [comment]
right on - I'll stop hitting `restart` over and over like a madman then
