### ISSUE TITLE
Mixing JCO/PST objects/filenames in instantiation

### ISSUE THREAD

**Issue by mnfienen** [jtwhite79/pyemu#58]
Bit of an obscure error here. When making a `LinearAnalysis` object (I was making a `Scur` object which calls the `LinearAnalysis` constructor) user can pass a string for `jco` or a `pyemu.Jco` object. 

So, if user passes a string for `jco`, `pyemu` replaces `.jco` or `.jcb` extension on the string with `.pst` and reads what it needs from that associated PEST control file.

But, if the user passes a `pyemu.Jco` object to the constructor, then there must also be a string or object for the `pst` argument to load from there. But.....if a user passes an object for `jco` and nothing for `pst`, `pyemu` is unable to find the PEST control file (tries to operate on `jco` like a string). 

I added an exception to handle this case and warn the user simply that if they provide an object for `jco` they must also pass an explicit `pst` arg. However, this is bombing a bunch of tests (tests that are intended to fail, but they fail without my new exception being caught and thus kill Travis). So....I propose we trap for these explicitly in the tests. However, I request a quick review to make sure that the intent of the tests is still met.

**Comment by jtwhite79** [comment]
I like better/more exception trapping and making the most with the args that are passed has been a focus with ``pyemu``...I guess one issue is that you don't need a ``Pst`` explicitly if you pass ``Jco`` and ``Cov``s for parameter prior and obs noise.  Why don't you check out a branch for this and can we work to make the behavior more intuitive (and get the tests working how we want)?

**Comment by mnfienen** [comment]
Right on. I also really like the flexibility in calls, so might need to amp up the exception handling in some of these to detect invalid combinations. Made a branch `la_exceptions` to explore this in
