### ISSUE TITLE
numbering of pst and par files

### ISSUE THREAD

**Issue by mnfienen** [jtwhite79/pyemu#6]
I was going to change this myself and do a pull request, but wasn't sure how deep the implications are:

when writing out multiple pest control files with `write_psts` method of a `MonteCarlo` object, numbering starts at 0.

but....when wither writing out individual par files with `parensemble.to_parfiles` or a big csv file with `parensemble.to_csv`, numering starts at 1. In the code for `to_parfiles` it is using the index rather than just iterating over a range (as it does in `write_psts`).  To integrate most cleanly with HTCondor, I'd love to see zero-based numbering throughout, but in any case, it would be good if the PST and PAR files were consistent one way or the other.

**Comment by jtwhite79** [comment]
great point.  I've sync'd the par and pst file naming so that everything starts at 0 with any zero padding...should help with condor

**Comment by mnfienen** [comment]
Killer! Thanks!
