### ISSUE TITLE
Zero variance with pyemu.Cov.from_parameter_data despite valid parbnds?

### ISSUE THREAD

**Issue by wkitlasten** [jtwhite79/pyemu#60]
I am trying to build a prior parameter covariance matrix from parameter bounds. 

pst=pyemu.Pst('pcf.pst')
cov = pyemu.Cov.from_parameter_data(pst)

Gives the following:
Exception: Cov.from_parameter_data() error: variance for parameter 10309025a1 is 0.0

The relevant line in the pst file is:

10309025a1	log	factor	3.221851906E+00	1.000000000E-06	4.000001000E+00	inflow	1.000000000E+00	-2.000001000E+00	1.000000000E+00

from pst.parameter_data.loc['10309025a1',:]

parnme       10309025a1
partrans            log
parchglim        factor
parval1         3.22185
parlbnd           1e-06
parubnd               4
pargp            inflow
scale                 1
offset               -2
dercom                1
extra               NaN
Name: 10309025a1, dtype: object

Changing parlbnd from 4.0 to 5.0 gets gets beyond parameter 10309025a1. Strange, of just me?

(won't let me attach control file)

**Comment by wkitlasten** [comment]
zip it... duh

[pcf_8015_1.zip](https://github.com/jtwhite79/pyemu/files/2280705/pcf_8015_1.zip)

**Comment by jtwhite79** [comment]
Looks like this is result of applying ``scale`` and ``offset`` the bounds before taking the log transform - in this case, that causes ``np.abs(parubnd) == np.abs(parlbnd)``.  I remember this happening before and there an option to help:  you can pass ``scale_offset=False`` to ``Cov .from_parameter_data()`` not apply ``scale`` and ``offset``.  I don't have a good answer as to conceptually whether these should or shouldn't be applied - any thoughts?

If you are accessing ``Cov.from_parameter_data()`` indirectly through helper function, you might not have access to ``scale_offset`` - let me know if we need to weave it through...

**Comment by wkitlasten** [comment]
Confirmed that offset was the problem. Switched these pars to no transformation. Cov.from_parameter_data() works fine now.

Correct, geostatistical_prior_builder does not see scale_offset.

**Comment by jtwhite79** [comment]
I've added a more verbose error message, suggesting to try changing ``scale_offset``.  

Also, I'm planning to refactor most of the higher-level draw methods to support the newly created ``from_mixed_draws`` and I'll add ``kwargs`` to all of these higher level draws...
