### ISSUE TITLE
Issue with regularization and parameters containing "-" in name

### ISSUE THREAD

**Issue by mnfienen** [jtwhite79/pyemu#66]
When parameter names contain "-" character (kinda bad form, but legal in PEST according to manual) there is a bug in `Pst.write()` when prior information has been implemented using `zero_order_tikhonov`. In the `Pst-write()` method, there is a call to private function `_parse_pi_par_names` which splits each prior information equation on `+` or `-`. 

As a result, the function concludes that the name pulled from the equation (which splits up names with a `-` in them) is invalid and removes all the prior information equations prior to writing the files.

The fix I suggest would be to check whether each parameter name is in an equation (likely very expensive). Not sure best other choice except maybe warn users if they use a `-` in a parameter name?

**Comment by jtwhite79** [comment]
There might be an easy fix: the specification for PI equations is that all tokens are whitespace separated, so instead of splitting on `+` and `-`, we could split on ` + ` and ` - ` (a space on each side of the operator.

**Comment by mnfienen** [comment]
I'm down with that solution - but.....does PEST require whitespace to delimit the equation elements?

**Comment by jtwhite79** [comment]
page 102 (BOOM!): 
> Each item on a prior information line must be separated from its neighbouring items by at least one space

**Comment by mnfienen** [comment]
Sweet as! On it.

**Comment by mnfienen** [comment]
OK - fixed this but had to do some "clever" coding. simply splitting on `" + "` and `" - "` was harder than one would think!
