### ISSUE TITLE
setup_hob in helpers.py fails to get hob_out_fname

### ISSUE THREAD

**Issue by corcorf** [jtwhite79/pyemu#71]
I've just been trying out the 'notest_MODFLOW_to_PEST_even_more_boss' example notebook and I think I've run into a bug:
- 'setup_hob' calls flopy's 'get_output_attribute' function to get the head observation output filename, but doesn't pass 'fname' to the 'attr' field. 
- as a result, 'get_output_attribute' doesn't return anything and the 'os.path.join()' call fails.
(I guess it's also possibly an issue that flopy doesn't give an error when no 'attr' is passed to 'get_output_attribute).

Loving your work.
F

**Comment by jwhite-usgs** [comment]
that notebook wasnt running - thanks for the heads up.  Its been patched on `develop` and I'll try to get it running with travis and appveyor before the next release.  But I dont think that version of the freyberg model uses `hob` so there should be an exception thrown if `setup_hob()` is called - if you want to include `hob` observations, then you need to add an `hob` package to the modflow model (and run it) first.  Is that what you were trying to do?

**Comment by corcorf** [comment]
Yes, sorry - should have said I was trying to adapt the notebook to a model of my own, which does include the `hob` package, when I got the error.
Thanks.

**Comment by jwhite-usgs** [comment]
right on - there are quite a few examples of the `PstFromFlopy` class in `autotest/full_meal_deal_tests.py` and `autotest/pst_tests.py` if you are looking for more examples.  I'll take another look at `setup_hob()`

**Comment by corcorf** [comment]
Thanks for the pointer to those examples. I think I've found a couple of other issues related to the above: 

1. when `setup_hob` is called it creates the `.hob.out.ins` file in the original model workspace, rather than in the new one. This means that when `build_pst` is called it misses the `hob.out.ins` file. I got around this by copying the `.ins` file over to my new model workspace.

2. `Pst.from_io_files` seems to read in all observation names as lower case. Not sure if this is by design, but for me it led to some pandas indexing errors when `build_pst` was called. When I changed all my observation names to lower case the error went away.

**Comment by jwhite-usgs** [comment]
Alright - I think I fixed the issue with the ins file being written to the old model workspace (on `develop`).  There is also a chance the hob-created obs names were not lower case explicitly, so those are being cast down now.  was the pandas indexing error in observation data?

**Comment by corcorf** [comment]
Yes - it happened when `build_pst` tried to copy the information from `obs_dfs['hob']` into the `obs` DataFrame. Because the `.hob.out.ins` file wasn't picked up when creating the `pst` object (and also because of the case issue), there were no rows in the `obs` DF for the head observations, and the `obs.loc` method failed (currently at line 2831).

**Comment by jwhite-usgs** [comment]
Sorry for the continued issues - I'm not an HBO guy myself and I need to just stop being lazy and add hob to one of the tests.  I think you are right about the path split.

Re forking, always looking for more contributors so please submit PRs at will!

**Comment by jmcdowell-usgs** [comment]
@jtwhite79 I see this is a couple years old but I am actually getting this same issue with 'get_output_attribute' for the HOB package. Was your fix ever pushed to the master branch? (I'm using v. 1.1.0)

**Comment by jtwhite79** [comment]
@jmcdowell-usgs - does the fix that @corcorf used work for you also?

`self.tmp_files.append(os.path.split(hob_out_fname))`
to
`self.tmp_files.append(os.path.split(hob_out_fname)[-1])`
