### ISSUE TITLE
adjust_weights_by_list

### ISSUE THREAD

**Issue by mnfienen-usgs** [jtwhite79/pyemu#77]
So this method has a bit of strange behavior. You can pass a list and a weight and the weights in the observation data section whose names are on the passed list get assigned the new weight. All good - BUT - there is a line in the code that restricts this behavior to only observations that start with a weight of 0.0. A couple thoughts on this:
0) at a minimum, the documentation should make this clear. I've been working with a user who had been trying to run this and could not figure out why no weights were being updated (and the reason is that the weights start with nonzero values)
1) we could make an option regarding nonzero existing weights
2) we could remove this method completely because it can easily be implemented directly in Pandas on the observation_data dataframe like:
pst.observation_data.loc[obslist, 'weight'] = new_weight

Open to ideas, but as it is, I think the documentation can lead to confusion.

**Comment by jwhite-usgs** [comment]
I'm inclined to remove this one - as you say, it's a trivial one liner.  I think we should reserve the "weight adjustment" methods for changing weights from current values ("adjust") in ways that require more than one line!

**Comment by mnfienen-usgs** [comment]
I'm down - let's do it.
