### ISSUE TITLE
PstFromFlopyModel fails when use_pp_zones==False but ibound includes values>1

### ISSUE THREAD

**Issue by corcorf** [jtwhite79/pyemu#78]
I was having trouble getting `PstFromFlopyModel` to run with my model when using only pilot point properties (no `grid_props` or `grid_props`). This stopped being an issue when I replaced all non-zero values in my ibound array with ones. I think `setup_pilotpoints_grid` was only creating pps where ibound==1, and as a result the helper crashed out during calculation of interpolation factors.
The documentation says that if `use_pp_zones` is False, ibound values greater than zero are treated as a single zone for pilot points, but this doesn't seem to be the case at present.

Code and error:

`pp_props = [["upw.{}".format(p),l] for p in ["hk","vka","ss","sy"] for l in range(nlay)]`
`helper = pyemu.helpers.PstFromFlopyModel(m, new_model_ws, model_exe_name='mfnwt', pp_props=pp_props,remove_existing=True,pp_space=4,use_pp_zones=False,build_prior=True)`

~/miniconda3/envs/flopy/lib/python3.7/site-packages/pyemu/utils/helpers.py in __init__(...)
   1717         self.setup_list_pars()
-> 1718         self.setup_array_pars()

~/miniconda3/envs/flopy/lib/python3.7/site-packages/pyemu/utils/helpers.py in setup_array_pars(self)
   2483         if self.pp_suffix in mlt_df.suffix.values:
   2484             self.log("setting up pilot point process")
-> 2485             self.pp_prep(mlt_df)

~/miniconda3/envs/flopy/lib/python3.7/site-packages/pyemu/utils/helpers.py in pp_prep(self, mlt_df)
-> 2270                     ok_pp.calc_factors_grid(self.m.sr, var_filename=var_file, zone_array=ib_k)

~/miniconda3/envs/flopy/lib/python3.7/site-packages/pyemu/utils/geostats.py in calc_factors_grid(self, spatial_reference, zone_array, minpts_interp, maxpts_interp, search_radius, verbose, var_filename, forgive)
    776             if self.interp_data is None or self.interp_data.dropna().shape[0] == 0:
--> 777                 raise Exception("no interpolation took place...something is wrong")

Exception: no interpolation took place...something is wrong

**Comment by jtwhite79** [comment]
Correct again - I just pushed a fix for this to `develop`.  Let me know if that doesn't work.

**Comment by corcorf** [comment]
Awesome, thanks.
