### ISSUE TITLE
Ensemble Smoother Example Notebook.

### ISSUE THREAD

**Issue by dpphat** [jtwhite79/pyemu#82]
Hi Jeremy. 
Thanks so much for your work on the pyEmu library.
Do you have any notebooks in which you demonstrate setting up of an iterative ensemble smoother that you are able to share?
Thanks again.
Dan Puddephatt

**Comment by jtwhite79** [comment]
Hey Dan - not sure if you have seen these:

[https://github.com/mnfienen-usgs/GW1876/tree/fy19/activities_csiro/notebooks](https://github.com/mnfienen-usgs/GW1876/tree/fy19/activities_csiro/notebooks)

you have to run the setup_pest_interface and prior_montecarlo notebooks first, but then you can run the pestpp-ies notebook, which includes a demo of full spatial localization setup.  That setup_pest_interface notebook shows how to programmatically setup a PEST interface for a MODFLOW-2005 family model... 

In general, PESTPP-IES can be run "as is" for an existing PEST interface but offers lots of fine-grained control through optional "++" args.  Have you seen the documentation in the USGS PESTPP repo?:

[https://github.com/usgs/pestpp](https://github.com/usgs/pestpp)

**Comment by dpphat** [comment]
Thanks so much Jeremy!
I am consulting the PESTpp manual. 
Mike's notebooks should be super-helpful in terms of having a PyEMU example to work with. 
Much appreciated. 
Dan
