### ISSUE TITLE
pestpp-ies build error resolved.

### ISSUE THREAD

**Issue by dpphat** [jtwhite79/pyemu#85]
Hi Jeremy. 
Thanks for your help resolving the template build issue I was having over on [usgs\pestpp ](https://github.com/usgs/pestpp/issues/18). The issue that you found was that the prior.jcb included negative numbers. I was building prior.jcb with an ensemble I prepared using pyEmu without enforcing parameter bounds. 

I was attempting to follow the [setup_pest_interface.pdf](https://github.com/mnfienen-usgs/GW1876/blob/fy19/activities_csiro/notebooks/setup_pest_interface.pdf) workflow presented on the mnfienen-usgs/GW1876 GitHub page; however, as I was using FEFLOW I was not able to use the pyemu.helpers.PstFromFlopyModel to build the ensemble. It turns out I selected the wrong utility as an alternative.

Instead, what I should have used is the pyemu.ParameterEnsemble.from_gaussian_draw with enforce_bounds set to 'True'. Pestpp-ies is now running.

Thank you so much for your assistance. I was not sure where to begin to debug my workflow (after several wrong turns before asking for help).

**Comment by jtwhite79** [comment]
Sweet @dpphat - I was worried something was up with the ensemble draw routine.  Glad it's working.
