### ISSUE TITLE
various utils rely on inschek

### ISSUE THREAD

**Issue by wkitlasten** [jtwhite79/pyemu#88]
Several examples and utils rely on inschek.exe. Is it possible to add inschek to the bin? If so, I will do the menial task of changing the run('inschek...) commands to the relative path so Windows users don't have to deal with another download and changing their path in environment variables.

**Comment by jtwhite79** [comment]
actually @wkitlasten I just finished adding python-based instruction file processing (checkout `Pst.processing_output_files()`).  This is still pretty green and doesnt support all the complexity of instructions that are possible but it does support the most common instructions (at least that I use).  So those calls to inschek are getting phased out and replaced by the python-based processor.  Any particular utils are causing you issues?  If you are going to add calls to `inschek` I recommend `os_utils.run` - it will eliminate issues around the leading `./` on linux and the `.exe` suffix on windows. 

On a related note, I think it would be really nice to have statically-linked binaries for the most common pest utils included with pyemu (with some nice python wrappers as needed), I just dont have the `make` skills to get them all built for the 3 main OS's.

**Comment by wkitlasten** [comment]
Busy man!

Calls to inschek using os_utils.run are in setup_mflist_budget_obs
and setup_mtlist_budget_obs (maybe others?).
setup_mflist_budget_obs returns None when inschek fails, so maybe the best
option is to just remove the "return None"? The user will get the error
message but (hopefully) the df will be returned for examination...?

**Comment by jtwhite79** [comment]
ok - I think we should migrate all those raw `os.system("inschek...")` calls to use `pst_utils.try_process_ins_file()` - this will use the new python-based instruction processing, esp since those utils write really simple instruction files.   I can work that in pretty soon otherwise PRs accepted!

**Comment by jtwhite79** [comment]
This should be done now - all instruction file processing should use `pyemu.pst_utils.InstructionFile`
