### ISSUE TITLE
obslist_dict

### ISSUE THREAD

**Issue by mnfienen** [jtwhite79/pyemu#9]
Thinking of a tiny refactor for the data/parameter importance methods. One of the optional inputs is the `obslist_dict`. But, since this is typically a dictionary with a list as the keys and the values, I suggest allowing users to supply only the list and then make the dict internally. If so, it would make sense to change the input arg from `obslist_dict` to `obslist` and similarly `parlist_dict` to `parlist`

I already implemented it in my fork. If you think it's ok, I will submit a pull request.

**Comment by jtwhite79** [comment]
The reason I went with ``obslist_dict`` and ``parlist_dict`` is to try make it clear what is going on:  the keys are the names of user-defined groupings of obs or pars to test.  For example 
``>>>obslist_dict['heads'] = ['head1',head2','head3']``
``>>>obslist_dict["fluxes'] = ['flux1','flux2','flux3']``
where ``['heads','fluxes']`` ends up being the index of the dataframe that is returned, with the idea being that this makes it easy pass a ``pandas.DataFrame.groupby().groups`` dictionary, and/or lets you give more meaningful names to the grouping you chose.  If you don't pass ``obslist_dict`` or ``parlist_dict``, then you get a datafame where the index is all of the (adjustable) pars or (non-zero) obs.  

Does that make sense? I think we could support list and dict - we could check the ``type`` of ``obslist_dict``/``parlist_dict`` inside the method.

**Comment by mnfienen** [comment]
Oh ok. That makes sense -- I just didn't grok that from the examples. Let's try to make it more explicit. In the examples we ended up with a `dict` made like `dict(zip(obslist,obslist))` which seemed redundant. Now I see the reason for that --- it was that in our example we only had a single group. I think we can just clarify it in the examples then. My implementation did the `type` check like you suggested above and makes the `dict` inside the method, so I'll still submit a pull request, but we can explain the `dict` behavior more explicitly and treat the `list` style as a special case. Cool?

**Comment by jtwhite79** [comment]
that works for me
