### ISSUE TITLE
parameter names too long, hk template file too wide

### ISSUE THREAD

**Issue by RebeccaDoble** [jtwhite79/pyemu#93]
Just in case Matt doesn't get back to me...

My pest setup is auto-generating parameter names that are longer than 12 characters (for simple stuff like hk and porosity). Also due to the size of the model (168 cols), the hk template file is too wide (> 2000 characters). Pest ++ is not impressed and won't run.

Apparently there is a switch for the setup pest file command to shorten the names. Could someone please show me where this is?

Many thanks,
Rebecca

**Comment by MJKnowling** [comment]
@RebeccaDoble PEST++ tools should have no problem with parnme string lengths greater than 12 char (the limit is 200) and template file line lengths greater than 2000 (I think the limit is 200K). These look like PEST limits (at least the parnme string length). There is even a new jco format that is triggered automatically when the old parnme limit is exceeded in PEST++. 

First things first, which exe are you calling and where/when did you get it? Did you pull it recently from the develop branch of the usgs/pestpp repo? Check this first!

**Comment by RebeccaDoble** [comment]
@MJKnowling yes, it is 4th October version of pestpp-ies.exe. 
I've just tried running it in a dos window now, and it worked. I'm going to have to double check why it doesn't in the notebook. One step closer... 

Thanks.

**Comment by MJKnowling** [comment]
@RebeccaDoble cool - just an exe path specification issue then by the sounds of it.
